# Generated by Django 3.2.15 on 2022-09-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('studios', models.CharField(max_length=200)),
                ('producers', models.CharField(max_length=200)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
    ]
